### ISSUE TITLE
Delete repository?

### ISSUE THREAD

**Issue by ghost** [FGMEMBERS/SpaceShuttle#5]
Though it may be legal, the author(s)/main author of this project seem to be not happy to have it here which is causing disputes (https://forum.flightgear.org/viewtopic.php?f=3&t=30362&start=135) so maybe it would be better, also out of respect, to delete this repository?

**Comment by JWocky** [comment]
One author, out of many in this project, tries license scam and tries for political reasons his hand perpetually in libel and slander. How does thart cause respect and why should it make us surrender to a bully?

**Comment by ghost** [comment]
I don't know any author who thinks it's good to have the SpaceShuttle in FGMEMBERS (pls correct me), but I know one, Thorsten, who has problems with it, and IMO one should honor the HUGE efforts he put into it.

**Comment by IAHM-COL** [comment]
I am also an author of this project, and I am not interested in remove my
own work.

**Comment by JWocky** [comment]
Maybe Herby likes to be removed? Maybe Wibrag? Maybe ... oh wait, we can't be sure how many authors are there in fact because Thorsten, in another illegal icense scam removed other Authors from the copyrights. See, the model is not from Thorsten, many of the smaller parts are not from Thorsten. A lot of work was done by others ... Thorsten only made some very visible things and then yelled around how cool he is and why laws and license right doesn't apply to him. There is not much to honour in what Thorsten did. What do you want to honour? Forging copyright files? License scam?

**Comment by FGDATA** [comment]
The model is from NASA. and modified by HerbyW, firefly, Michat and others
Cockpits models are from C. Khun
Initial FDM was by JSBerndt.

Furthermore, some of the content was made by me. Making me an authors. 

If Thorsten collects signatures of all authors (even those he fails to list) to remove the GPL from this content and they all agree to remove it from FGADDon, I probably will still not give my grant. Therefore I dont see how this work will be loosing GPL status.
